// ---------------------------------------------------------------------------
// SEO role dataset – 120+ common job roles with per-role ATS keywords.
// Used by /resume/[role] pages for programmatic SEO traffic generation.
// ---------------------------------------------------------------------------

export type SeoRole = {
  /** URL-safe slug, e.g. "backend-engineer" */
  slug: string;
  /** Human-readable job title */
  title: string;
  /** 10–20 ATS-relevant keywords for the role */
  keywords: string[];
};

// prettier-ignore
const ROLES: SeoRole[] = [
  // ── Engineering ──────────────────────────────────────────────────────
  { slug: "software-engineer",           title: "Software Engineer",           keywords: ["algorithms", "data structures", "system design", "unit testing", "code review", "git", "ci/cd", "agile", "rest api", "microservices", "cloud", "troubleshooting", "performance optimization", "documentation"] },
  { slug: "backend-engineer",            title: "Backend Engineer",            keywords: ["node.js", "rest api", "distributed systems", "docker", "microservices", "sql", "aws", "kubernetes", "caching", "message queues", "api design", "monitoring", "postgresql", "redis", "load balancing"] },
  { slug: "frontend-developer",          title: "Frontend Developer",          keywords: ["react", "typescript", "html", "css", "responsive design", "accessibility", "webpack", "performance", "state management", "testing", "figma", "component libraries", "next.js", "browser apis"] },
  { slug: "full-stack-developer",        title: "Full Stack Developer",        keywords: ["react", "node.js", "typescript", "sql", "rest api", "git", "docker", "cloud", "ci/cd", "testing", "database design", "responsive design", "agile", "devops", "monitoring"] },
  { slug: "mobile-developer",            title: "Mobile Developer",            keywords: ["react native", "swift", "kotlin", "ios", "android", "mobile ui", "app store", "push notifications", "offline storage", "rest api", "ci/cd", "performance profiling", "accessibility"] },
  { slug: "android-developer",           title: "Android Developer",           keywords: ["kotlin", "java", "android sdk", "jetpack compose", "room", "retrofit", "coroutines", "mvvm", "unit testing", "google play", "gradle", "material design", "dependency injection", "ci/cd"] },
  { slug: "ios-developer",               title: "iOS Developer",               keywords: ["swift", "swiftui", "uikit", "core data", "combine", "xcode", "cocoapods", "auto layout", "unit testing", "app store connect", "accessibility", "push notifications", "rest api", "ci/cd"] },
  { slug: "devops-engineer",             title: "DevOps Engineer",             keywords: ["docker", "kubernetes", "terraform", "ci/cd", "aws", "linux", "monitoring", "infrastructure as code", "ansible", "jenkins", "github actions", "logging", "security", "networking", "helm"] },
  { slug: "cloud-engineer",              title: "Cloud Engineer",              keywords: ["aws", "azure", "gcp", "terraform", "cloudformation", "networking", "iam", "kubernetes", "serverless", "cost optimization", "monitoring", "security", "high availability", "load balancing"] },
  { slug: "site-reliability-engineer",   title: "Site Reliability Engineer",   keywords: ["sre", "monitoring", "incident response", "sla", "slo", "observability", "automation", "linux", "kubernetes", "terraform", "on-call", "postmortems", "capacity planning", "chaos engineering"] },
  { slug: "security-engineer",           title: "Security Engineer",           keywords: ["penetration testing", "vulnerability assessment", "siem", "encryption", "iam", "soc", "compliance", "threat modeling", "firewalls", "owasp", "incident response", "cloud security", "zero trust"] },
  { slug: "qa-engineer",                 title: "QA Engineer",                 keywords: ["test automation", "selenium", "cypress", "test plans", "regression testing", "bug tracking", "ci/cd", "api testing", "load testing", "manual testing", "quality assurance", "agile", "jira"] },
  { slug: "machine-learning-engineer",   title: "Machine Learning Engineer",   keywords: ["python", "tensorflow", "pytorch", "scikit-learn", "model training", "feature engineering", "mlops", "data pipelines", "deep learning", "nlp", "computer vision", "experiment tracking", "aws sagemaker", "docker"] },
  { slug: "data-engineer",               title: "Data Engineer",               keywords: ["sql", "python", "spark", "airflow", "etl", "data warehousing", "snowflake", "redshift", "kafka", "dbt", "data modeling", "cloud", "data quality", "batch processing", "streaming"] },
  { slug: "platform-engineer",           title: "Platform Engineer",           keywords: ["kubernetes", "docker", "terraform", "internal developer platform", "ci/cd", "service mesh", "observability", "gitops", "automation", "infrastructure as code", "aws", "api gateway", "developer experience"] },
  { slug: "embedded-systems-engineer",   title: "Embedded Systems Engineer",   keywords: ["c", "c++", "rtos", "firmware", "microcontrollers", "arm", "jtag", "i2c", "spi", "uart", "pcb design", "debugging", "low power", "linux kernel"] },
  { slug: "network-engineer",            title: "Network Engineer",            keywords: ["tcp/ip", "dns", "vpn", "firewall", "routing", "switching", "cisco", "load balancing", "bgp", "ospf", "network monitoring", "troubleshooting", "sdn", "cloud networking"] },
  { slug: "database-administrator",      title: "Database Administrator",      keywords: ["postgresql", "mysql", "sql server", "oracle", "backup and recovery", "replication", "performance tuning", "indexing", "query optimization", "high availability", "monitoring", "security", "migration"] },
  { slug: "systems-administrator",       title: "Systems Administrator",       keywords: ["linux", "windows server", "active directory", "vmware", "bash", "powershell", "monitoring", "backup", "networking", "patch management", "dns", "dhcp", "automation", "troubleshooting"] },
  { slug: "software-architect",          title: "Software Architect",          keywords: ["system design", "microservices", "domain driven design", "event driven architecture", "api design", "scalability", "cloud", "security", "documentation", "technical leadership", "stakeholder management", "performance"] },
  { slug: "solutions-architect",         title: "Solutions Architect",         keywords: ["aws", "azure", "system design", "cloud migration", "enterprise architecture", "cost optimization", "security", "networking", "stakeholder management", "documentation", "high availability", "compliance"] },
  { slug: "engineering-manager",         title: "Engineering Manager",         keywords: ["team leadership", "agile", "hiring", "mentoring", "sprint planning", "performance reviews", "roadmap", "cross-functional", "technical strategy", "incident management", "delivery", "stakeholder management"] },
  { slug: "technical-lead",              title: "Technical Lead",              keywords: ["code review", "architecture", "mentoring", "system design", "agile", "delivery", "technical decisions", "documentation", "cross-functional", "performance", "best practices", "risk assessment"] },
  { slug: "release-engineer",            title: "Release Engineer",            keywords: ["ci/cd", "release management", "branching strategy", "deployment automation", "rollback", "version control", "build systems", "monitoring", "testing", "change management", "documentation"] },
  { slug: "java-developer",              title: "Java Developer",              keywords: ["java", "spring boot", "hibernate", "microservices", "rest api", "maven", "gradle", "junit", "sql", "docker", "aws", "multithreading", "design patterns", "kafka"] },
  { slug: "python-developer",            title: "Python Developer",            keywords: ["python", "django", "flask", "fastapi", "rest api", "sql", "celery", "docker", "aws", "testing", "asyncio", "data structures", "oop", "ci/cd"] },
  { slug: "react-developer",             title: "React Developer",             keywords: ["react", "typescript", "redux", "next.js", "hooks", "context api", "testing library", "css-in-js", "graphql", "rest api", "performance", "accessibility", "responsive design", "storybook"] },
  { slug: "golang-developer",            title: "Golang Developer",            keywords: ["go", "goroutines", "channels", "rest api", "grpc", "docker", "kubernetes", "microservices", "sql", "concurrency", "testing", "performance", "cloud", "monitoring"] },
  { slug: "rust-developer",              title: "Rust Developer",              keywords: ["rust", "ownership model", "concurrency", "systems programming", "wasm", "cli tools", "performance", "memory safety", "cargo", "testing", "async", "embedded", "linux"] },
  { slug: "sql-developer",               title: "SQL Developer",               keywords: ["sql", "stored procedures", "query optimization", "indexing", "database design", "etl", "reporting", "data modeling", "postgresql", "sql server", "mysql", "performance tuning"] },
  { slug: "wordpress-developer",         title: "WordPress Developer",         keywords: ["wordpress", "php", "themes", "plugins", "woocommerce", "html", "css", "javascript", "mysql", "seo", "responsive design", "gutenberg", "rest api", "hosting"] },
  { slug: "blockchain-developer",        title: "Blockchain Developer",        keywords: ["solidity", "ethereum", "smart contracts", "web3", "defi", "nft", "rust", "cryptography", "consensus", "hardhat", "testing", "security auditing", "tokenomics"] },
  { slug: "game-developer",              title: "Game Developer",              keywords: ["unity", "unreal engine", "c#", "c++", "game physics", "3d math", "shaders", "multiplayer", "optimization", "animation", "game design", "version control", "debugging"] },
  { slug: "support-engineer",            title: "Support Engineer",            keywords: ["troubleshooting", "ticketing systems", "linux", "networking", "customer communication", "documentation", "escalation", "sql", "scripting", "monitoring", "sla", "root cause analysis"] },
  { slug: "it-support-specialist",       title: "IT Support Specialist",       keywords: ["helpdesk", "windows", "macos", "active directory", "networking", "troubleshooting", "ticketing", "hardware", "remote support", "documentation", "customer service", "security"] },
  { slug: "technical-support-specialist", title: "Technical Support Specialist", keywords: ["troubleshooting", "ticketing", "api debugging", "log analysis", "customer communication", "documentation", "sql", "escalation", "saas", "monitoring", "sla", "product knowledge"] },
  { slug: "automation-engineer",         title: "Automation Engineer",         keywords: ["python", "selenium", "ci/cd", "test automation", "scripting", "robot framework", "api testing", "jenkins", "docker", "bash", "monitoring", "infrastructure as code", "ansible"] },

  // ── Data & Analytics ─────────────────────────────────────────────────
  { slug: "data-scientist",              title: "Data Scientist",              keywords: ["python", "machine learning", "statistics", "sql", "pandas", "scikit-learn", "deep learning", "experimentation", "data visualization", "a/b testing", "feature engineering", "jupyter", "r", "storytelling"] },
  { slug: "data-analyst",                title: "Data Analyst",                keywords: ["sql", "excel", "tableau", "power bi", "python", "data visualization", "reporting", "dashboards", "statistics", "stakeholder management", "etl", "business intelligence", "data cleaning"] },
  { slug: "business-intelligence-analyst", title: "Business Intelligence Analyst", keywords: ["sql", "tableau", "power bi", "looker", "data modeling", "dashboards", "etl", "reporting", "kpis", "data warehousing", "stakeholder management", "excel", "storytelling"] },
  { slug: "analytics-engineer",          title: "Analytics Engineer",          keywords: ["sql", "dbt", "snowflake", "data modeling", "etl", "python", "git", "data quality", "dashboards", "testing", "documentation", "data warehousing", "ci/cd"] },
  { slug: "quantitative-analyst",        title: "Quantitative Analyst",        keywords: ["python", "r", "statistics", "financial modeling", "stochastic calculus", "time series", "risk analysis", "sql", "monte carlo", "optimization", "machine learning", "matlab"] },
  { slug: "research-scientist",          title: "Research Scientist",          keywords: ["python", "machine learning", "deep learning", "publications", "experimentation", "statistics", "pytorch", "nlp", "computer vision", "research methodology", "data analysis", "collaboration"] },

  // ── Product & Program Management ─────────────────────────────────────
  { slug: "product-manager",             title: "Product Manager",             keywords: ["roadmap", "user research", "prioritization", "go-to-market", "metrics", "backlog", "stakeholder management", "discovery", "a/b testing", "cross-functional", "requirements", "launch", "okrs", "analytics"] },
  { slug: "senior-product-manager",      title: "Senior Product Manager",      keywords: ["product strategy", "roadmap", "stakeholder alignment", "go-to-market", "metrics", "team leadership", "user research", "market analysis", "prioritization", "okrs", "launch", "analytics", "cross-functional"] },
  { slug: "product-analyst",             title: "Product Analyst",             keywords: ["sql", "analytics", "a/b testing", "dashboards", "product metrics", "funnel analysis", "cohort analysis", "experimentation", "python", "tableau", "user behavior", "stakeholder management"] },
  { slug: "technical-product-manager",   title: "Technical Product Manager",   keywords: ["api design", "system architecture", "roadmap", "agile", "sql", "developer experience", "stakeholder management", "technical requirements", "cross-functional", "prioritization", "documentation", "data pipelines"] },
  { slug: "program-manager",             title: "Program Manager",             keywords: ["program management", "cross-functional", "stakeholder management", "roadmap", "risk management", "resource planning", "agile", "reporting", "documentation", "change management", "communication", "budgeting"] },
  { slug: "technical-program-manager",   title: "Technical Program Manager",   keywords: ["program management", "cross-functional", "system design", "risk management", "agile", "stakeholder management", "technical requirements", "roadmap", "documentation", "incident management", "delivery"] },
  { slug: "project-manager",             title: "Project Manager",             keywords: ["project planning", "gantt charts", "risk management", "budgeting", "stakeholder management", "agile", "waterfall", "jira", "documentation", "resource allocation", "communication", "reporting"] },
  { slug: "technical-project-manager",   title: "Technical Project Manager",   keywords: ["project management", "agile", "technical requirements", "risk management", "cross-functional", "jira", "ci/cd", "stakeholder management", "budgeting", "documentation", "delivery"] },
  { slug: "scrum-master",                title: "Scrum Master",                keywords: ["scrum", "agile", "sprint planning", "retrospectives", "kanban", "jira", "facilitation", "coaching", "impediment removal", "velocity", "continuous improvement", "team dynamics", "stakeholder management"] },
  { slug: "chief-of-staff",              title: "Chief of Staff",              keywords: ["strategic planning", "cross-functional", "stakeholder management", "executive communication", "program management", "okrs", "reporting", "decision making", "organizational design", "board decks", "budgeting"] },

  // ── Design ───────────────────────────────────────────────────────────
  { slug: "product-designer",            title: "Product Designer",            keywords: ["figma", "user research", "wireframes", "prototyping", "design systems", "usability testing", "interaction design", "accessibility", "responsive design", "visual design", "collaboration", "journey mapping"] },
  { slug: "ux-designer",                 title: "UX Designer",                 keywords: ["user research", "wireframes", "prototyping", "usability testing", "journey mapping", "figma", "accessibility", "information architecture", "interaction design", "design thinking", "personas", "heuristic evaluation"] },
  { slug: "ui-designer",                 title: "UI Designer",                 keywords: ["figma", "visual design", "design systems", "typography", "color theory", "iconography", "responsive design", "component libraries", "prototyping", "brand identity", "accessibility", "css"] },
  { slug: "ux-researcher",               title: "UX Researcher",              keywords: ["user interviews", "usability testing", "surveys", "personas", "journey mapping", "a/b testing", "quantitative research", "qualitative research", "data analysis", "synthesis", "stakeholder presentations", "research ops"] },
  { slug: "visual-designer",             title: "Visual Designer",             keywords: ["adobe creative suite", "figma", "brand identity", "typography", "color theory", "layout", "illustration", "motion graphics", "design systems", "print", "digital", "photography"] },
  { slug: "art-director",                title: "Art Director",                keywords: ["creative direction", "brand strategy", "visual identity", "team leadership", "photography", "typography", "campaign development", "client management", "adobe creative suite", "storytelling", "production"] },
  { slug: "web-designer",                title: "Web Designer",                keywords: ["html", "css", "figma", "responsive design", "typography", "color theory", "ui design", "wordpress", "accessibility", "seo", "javascript", "prototyping", "brand consistency"] },
  { slug: "motion-designer",             title: "Motion Designer",             keywords: ["after effects", "cinema 4d", "animation", "motion graphics", "storyboarding", "video editing", "premiere pro", "3d", "visual storytelling", "brand animation", "social media content"] },
  { slug: "design-systems-lead",         title: "Design Systems Lead",         keywords: ["design tokens", "component libraries", "figma", "documentation", "accessibility", "css", "react", "storybook", "cross-functional", "governance", "design ops", "scalability"] },

  // ── Marketing ────────────────────────────────────────────────────────
  { slug: "marketing-manager",           title: "Marketing Manager",           keywords: ["campaign management", "analytics", "content strategy", "seo", "paid media", "email marketing", "lead generation", "branding", "go-to-market", "reporting", "cross-functional", "budget management"] },
  { slug: "digital-marketing-manager",   title: "Digital Marketing Manager",   keywords: ["seo", "sem", "google ads", "social media", "email marketing", "analytics", "conversion optimization", "content strategy", "a/b testing", "marketing automation", "attribution", "reporting"] },
  { slug: "product-marketing-manager",   title: "Product Marketing Manager",   keywords: ["positioning", "messaging", "go-to-market", "competitive analysis", "sales enablement", "launch planning", "personas", "market research", "content strategy", "cross-functional", "analytics", "storytelling"] },
  { slug: "content-marketer",            title: "Content Marketer",            keywords: ["content strategy", "seo", "blogging", "copywriting", "editorial calendar", "social media", "analytics", "storytelling", "email marketing", "content distribution", "keyword research", "cms"] },
  { slug: "growth-marketer",             title: "Growth Marketer",             keywords: ["growth loops", "a/b testing", "conversion optimization", "analytics", "paid acquisition", "seo", "product-led growth", "lifecycle marketing", "retention", "experimentation", "sql", "attribution"] },
  { slug: "demand-generation-manager",   title: "Demand Generation Manager",   keywords: ["lead generation", "marketing automation", "hubspot", "marketo", "campaigns", "paid media", "email marketing", "pipeline", "analytics", "conversion optimization", "abm", "webinars"] },
  { slug: "seo-specialist",              title: "SEO Specialist",              keywords: ["on-page seo", "off-page seo", "keyword research", "technical seo", "google analytics", "search console", "link building", "content optimization", "site audits", "schema markup", "page speed", "competitor analysis"] },
  { slug: "performance-marketer",        title: "Performance Marketer",        keywords: ["google ads", "facebook ads", "linkedin ads", "campaign optimization", "roas", "attribution", "a/b testing", "analytics", "retargeting", "conversion tracking", "budget management", "bid strategy"] },
  { slug: "social-media-manager",        title: "Social Media Manager",        keywords: ["content creation", "community management", "analytics", "social strategy", "instagram", "linkedin", "tiktok", "paid social", "engagement", "scheduling", "brand voice", "influencer marketing"] },
  { slug: "brand-manager",               title: "Brand Manager",               keywords: ["brand strategy", "positioning", "messaging", "market research", "competitive analysis", "creative direction", "campaign management", "analytics", "stakeholder management", "go-to-market", "brand guidelines"] },
  { slug: "copywriter",                  title: "Copywriter",                  keywords: ["copywriting", "brand voice", "seo writing", "email copy", "landing pages", "headlines", "a/b testing", "storytelling", "editing", "content strategy", "product copy", "cta optimization"] },
  { slug: "email-marketing-specialist",  title: "Email Marketing Specialist",  keywords: ["email campaigns", "marketing automation", "segmentation", "a/b testing", "deliverability", "html email", "lifecycle marketing", "analytics", "personalization", "drip campaigns", "crm", "compliance"] },
  { slug: "event-marketing-manager",     title: "Event Marketing Manager",     keywords: ["event planning", "webinars", "conferences", "budgeting", "vendor management", "sponsorships", "lead generation", "logistics", "promotion", "stakeholder management", "analytics", "post-event reporting"] },
  { slug: "marketing-analyst",           title: "Marketing Analyst",           keywords: ["sql", "google analytics", "reporting", "dashboards", "attribution", "campaign analysis", "excel", "tableau", "a/b testing", "marketing mix modeling", "data visualization", "stakeholder management"] },
  { slug: "marketing-operations-manager", title: "Marketing Operations Manager", keywords: ["marketing automation", "hubspot", "marketo", "crm", "data hygiene", "reporting", "campaign ops", "lead scoring", "analytics", "process improvement", "integrations", "documentation"] },
  { slug: "ecommerce-manager",           title: "Ecommerce Manager",           keywords: ["shopify", "conversion optimization", "merchandising", "analytics", "seo", "paid media", "inventory management", "customer experience", "a/b testing", "email marketing", "upselling", "reporting"] },
  { slug: "video-editor",                title: "Video Editor",                keywords: ["premiere pro", "after effects", "davinci resolve", "color grading", "motion graphics", "sound design", "storytelling", "youtube", "social media", "pacing", "collaboration", "asset management"] },

  // ── Sales ────────────────────────────────────────────────────────────
  { slug: "account-executive",           title: "Account Executive",           keywords: ["pipeline", "prospecting", "negotiation", "crm", "salesforce", "quota attainment", "discovery", "presentations", "closing", "account planning", "forecasting", "stakeholder management", "contract negotiation"] },
  { slug: "enterprise-account-executive", title: "Enterprise Account Executive", keywords: ["enterprise sales", "complex deal cycles", "c-suite engagement", "negotiation", "crm", "solution selling", "pipeline", "stakeholder management", "forecasting", "account planning", "contract negotiation", "presentations"] },
  { slug: "sales-development-representative", title: "Sales Development Representative", keywords: ["prospecting", "cold outreach", "email sequences", "crm", "qualification", "pipeline generation", "salesforce", "objection handling", "discovery calls", "linkedin", "personalization", "cadence management"] },
  { slug: "sales-manager",               title: "Sales Manager",               keywords: ["team leadership", "pipeline management", "forecasting", "coaching", "hiring", "crm", "quota management", "sales strategy", "cross-functional", "reporting", "deal review", "performance management"] },
  { slug: "sales-engineer",              title: "Sales Engineer",              keywords: ["product demos", "technical requirements", "api", "proof of concept", "solution design", "crm", "stakeholder management", "rfp responses", "cross-functional", "presentations", "troubleshooting", "integrations"] },
  { slug: "solutions-consultant",        title: "Solutions Consultant",        keywords: ["consulting", "requirements gathering", "solution design", "presentations", "stakeholder management", "implementation", "crm", "product knowledge", "cross-functional", "documentation", "demos", "roi analysis"] },
  { slug: "account-manager",             title: "Account Manager",             keywords: ["account management", "renewals", "upselling", "customer relationships", "crm", "quarterly reviews", "retention", "stakeholder management", "contract negotiation", "forecasting", "cross-functional", "reporting"] },
  { slug: "inside-sales-representative", title: "Inside Sales Representative", keywords: ["cold calling", "email outreach", "crm", "pipeline", "prospecting", "quota", "objection handling", "product knowledge", "demos", "follow-up", "qualification", "salesforce"] },
  { slug: "customer-success-manager",    title: "Customer Success Manager",    keywords: ["onboarding", "retention", "renewals", "churn reduction", "health scores", "quarterly reviews", "stakeholder management", "product adoption", "crm", "upselling", "cross-functional", "reporting"] },
  { slug: "partnerships-manager",        title: "Partnerships Manager",        keywords: ["partnership development", "negotiation", "co-marketing", "channel sales", "contract management", "relationship management", "revenue", "cross-functional", "reporting", "go-to-market", "stakeholder management"] },
  { slug: "revenue-operations-manager",  title: "Revenue Operations Manager",  keywords: ["salesforce", "crm", "pipeline analytics", "forecasting", "data hygiene", "process improvement", "reporting", "dashboards", "cross-functional", "commission plans", "lead routing", "integration"] },
  { slug: "vp-sales",                    title: "VP of Sales",                 keywords: ["sales strategy", "team building", "forecasting", "board reporting", "enterprise sales", "pipeline", "hiring", "coaching", "cross-functional", "revenue growth", "market expansion", "leadership"] },
  { slug: "bdr-manager",                 title: "BDR Manager",                 keywords: ["team leadership", "coaching", "pipeline generation", "outbound strategy", "hiring", "cadence management", "crm", "reporting", "performance management", "training", "quota setting", "cross-functional"] },
  { slug: "technical-account-manager",   title: "Technical Account Manager",   keywords: ["technical support", "account management", "api", "integration", "renewals", "stakeholder management", "troubleshooting", "product adoption", "crm", "escalation", "documentation", "cross-functional"] },
  { slug: "business-development-manager", title: "Business Development Manager", keywords: ["lead generation", "partnership development", "market research", "pipeline", "negotiation", "prospecting", "crm", "go-to-market", "strategy", "presentations", "cross-functional", "revenue growth"] },

  // ── Operations ───────────────────────────────────────────────────────
  { slug: "operations-manager",          title: "Operations Manager",          keywords: ["process improvement", "automation", "cross-functional", "budgeting", "vendor management", "reporting", "kpis", "documentation", "risk management", "team leadership", "resource planning", "sops"] },
  { slug: "operations-analyst",          title: "Operations Analyst",          keywords: ["data analysis", "process improvement", "sql", "reporting", "dashboards", "automation", "documentation", "excel", "stakeholder management", "kpis", "vendor management", "cross-functional"] },
  { slug: "business-analyst",            title: "Business Analyst",            keywords: ["requirements gathering", "stakeholder management", "data analysis", "sql", "documentation", "process mapping", "jira", "agile", "reporting", "user stories", "wireframes", "cross-functional"] },
  { slug: "implementation-manager",      title: "Implementation Manager",      keywords: ["project management", "onboarding", "technical requirements", "stakeholder management", "documentation", "cross-functional", "training", "data migration", "api", "timelines", "risk management", "communication"] },
  { slug: "procurement-specialist",      title: "Procurement Specialist",      keywords: ["vendor management", "negotiation", "contract management", "cost analysis", "purchase orders", "compliance", "sourcing", "budgeting", "documentation", "risk assessment", "supply chain", "reporting"] },
  { slug: "supply-chain-analyst",        title: "Supply Chain Analyst",        keywords: ["supply chain", "demand forecasting", "inventory management", "logistics", "erp", "data analysis", "excel", "reporting", "cost optimization", "vendor management", "kpis", "process improvement"] },
  { slug: "customer-support-specialist", title: "Customer Support Specialist", keywords: ["ticketing", "troubleshooting", "customer communication", "zendesk", "sla", "documentation", "escalation", "product knowledge", "empathy", "multitasking", "crm", "feedback loops"] },
  { slug: "logistics-coordinator",       title: "Logistics Coordinator",       keywords: ["shipping", "inventory", "warehousing", "erp", "supply chain", "vendor coordination", "documentation", "scheduling", "cost management", "compliance", "tracking", "communication"] },

  // ── Finance & Accounting ─────────────────────────────────────────────
  { slug: "financial-analyst",           title: "Financial Analyst",           keywords: ["financial modeling", "forecasting", "excel", "budgeting", "variance analysis", "reporting", "dcf", "valuation", "sql", "presentation", "kpis", "strategic planning", "stakeholder management"] },
  { slug: "fp-and-a-analyst",            title: "FP&A Analyst",               keywords: ["financial planning", "budgeting", "forecasting", "variance analysis", "excel", "reporting", "kpis", "financial modeling", "stakeholder management", "revenue analysis", "headcount planning", "dashboards"] },
  { slug: "staff-accountant",            title: "Staff Accountant",            keywords: ["journal entries", "reconciliation", "gaap", "accounts payable", "accounts receivable", "month-end close", "excel", "erp", "audit support", "accruals", "financial statements", "compliance"] },
  { slug: "accounts-payable-specialist", title: "Accounts Payable Specialist", keywords: ["invoice processing", "vendor management", "reconciliation", "erp", "payment processing", "expense reporting", "compliance", "documentation", "excel", "month-end close", "accruals", "three-way match"] },
  { slug: "finance-manager",             title: "Finance Manager",             keywords: ["financial planning", "budgeting", "team leadership", "forecasting", "reporting", "compliance", "audit", "cash flow", "erp", "stakeholder management", "process improvement", "controls"] },
  { slug: "payroll-specialist",          title: "Payroll Specialist",          keywords: ["payroll processing", "tax compliance", "benefits administration", "hris", "time tracking", "multi-state payroll", "auditing", "documentation", "employee queries", "reporting", "regulations", "erp"] },
  { slug: "tax-analyst",                 title: "Tax Analyst",                 keywords: ["tax compliance", "tax returns", "income tax", "sales tax", "research", "tax planning", "excel", "erp", "audit support", "documentation", "regulations", "reporting"] },
  { slug: "controller",                  title: "Controller",                  keywords: ["financial statements", "gaap", "month-end close", "team leadership", "audit", "internal controls", "budgeting", "compliance", "erp", "cash flow", "reporting", "process improvement"] },
  { slug: "internal-auditor",            title: "Internal Auditor",            keywords: ["audit planning", "risk assessment", "internal controls", "compliance", "documentation", "testing", "reporting", "sox", "data analysis", "stakeholder management", "process improvement", "fraud detection"] },

  // ── People & HR ──────────────────────────────────────────────────────
  { slug: "recruiter",                   title: "Recruiter",                   keywords: ["sourcing", "screening", "interviewing", "ats", "candidate experience", "pipeline management", "employer branding", "offer negotiation", "hiring metrics", "linkedin", "diversity hiring", "stakeholder management"] },
  { slug: "technical-recruiter",         title: "Technical Recruiter",         keywords: ["technical sourcing", "github", "linkedin", "screening", "ats", "candidate experience", "pipeline management", "hiring metrics", "employer branding", "diversity hiring", "offer negotiation", "engineering hiring"] },
  { slug: "talent-acquisition-specialist", title: "Talent Acquisition Specialist", keywords: ["sourcing", "employer branding", "ats", "candidate experience", "interviewing", "pipeline management", "hiring metrics", "diversity hiring", "offer management", "onboarding", "stakeholder management", "linkedin"] },
  { slug: "hr-manager",                  title: "HR Manager",                  keywords: ["employee relations", "performance management", "compliance", "hris", "onboarding", "benefits administration", "policy development", "team leadership", "conflict resolution", "compensation", "training", "reporting"] },
  { slug: "people-operations-manager",   title: "People Operations Manager",   keywords: ["hris", "onboarding", "employee experience", "process improvement", "compliance", "data analysis", "reporting", "benefits", "performance management", "documentation", "automation", "cross-functional"] },
  { slug: "compensation-analyst",        title: "Compensation Analyst",        keywords: ["compensation benchmarking", "salary surveys", "pay equity", "hris", "excel", "job leveling", "total rewards", "data analysis", "reporting", "compliance", "market analysis", "stakeholder management"] },
  { slug: "learning-and-development-manager", title: "Learning and Development Manager", keywords: ["training programs", "curriculum design", "lms", "e-learning", "onboarding", "leadership development", "performance management", "facilitation", "needs assessment", "reporting", "vendor management", "coaching"] },

  // ── Legal & Compliance ───────────────────────────────────────────────
  { slug: "compliance-analyst",          title: "Compliance Analyst",          keywords: ["regulatory compliance", "risk assessment", "audit", "policy development", "documentation", "monitoring", "reporting", "sox", "gdpr", "training", "investigations", "internal controls"] },
  { slug: "legal-counsel",               title: "Legal Counsel",               keywords: ["contract review", "negotiation", "corporate law", "compliance", "intellectual property", "risk assessment", "litigation", "regulatory", "documentation", "stakeholder management", "privacy", "employment law"] },
  { slug: "privacy-engineer",            title: "Privacy Engineer",            keywords: ["gdpr", "ccpa", "data privacy", "privacy by design", "consent management", "data mapping", "encryption", "access controls", "compliance", "documentation", "risk assessment", "automation"] },
  { slug: "contract-manager",            title: "Contract Manager",            keywords: ["contract lifecycle", "negotiation", "redlining", "compliance", "vendor management", "risk assessment", "documentation", "clm software", "stakeholder management", "reporting", "templates", "renewal management"] },

  // ── Customer & Success ───────────────────────────────────────────────
  { slug: "customer-experience-manager", title: "Customer Experience Manager", keywords: ["customer journey", "nps", "csat", "feedback analysis", "process improvement", "cross-functional", "stakeholder management", "reporting", "cx strategy", "retention", "churn analysis", "documentation"] },
  { slug: "onboarding-specialist",       title: "Onboarding Specialist",       keywords: ["customer onboarding", "training", "documentation", "product adoption", "project management", "communication", "data migration", "troubleshooting", "crm", "stakeholder management", "sla", "reporting"] },

  // ── Miscellaneous / Emerging ─────────────────────────────────────────
  { slug: "ai-engineer",                 title: "AI Engineer",                 keywords: ["python", "llm", "prompt engineering", "rag", "langchain", "vector databases", "fine-tuning", "pytorch", "api design", "evaluation", "mlops", "cloud", "data pipelines", "responsible ai"] },
  { slug: "prompt-engineer",             title: "Prompt Engineer",             keywords: ["prompt design", "llm", "evaluation", "few-shot learning", "chain-of-thought", "retrieval augmented generation", "testing", "documentation", "python", "api", "fine-tuning", "responsible ai"] },
  { slug: "developer-advocate",          title: "Developer Advocate",          keywords: ["technical writing", "public speaking", "community management", "developer experience", "api", "tutorials", "open source", "documentation", "content creation", "product feedback", "events", "social media"] },
  { slug: "crm-administrator",           title: "CRM Administrator",           keywords: ["salesforce", "hubspot", "crm configuration", "data hygiene", "workflow automation", "reporting", "dashboards", "integrations", "user management", "training", "documentation", "process improvement"] },
  { slug: "data-privacy-officer",        title: "Data Privacy Officer",        keywords: ["gdpr", "ccpa", "privacy policy", "data mapping", "risk assessment", "dpia", "compliance", "training", "vendor assessment", "incident response", "documentation", "stakeholder management"] },
  { slug: "sustainability-analyst",      title: "Sustainability Analyst",      keywords: ["esg reporting", "carbon accounting", "sustainability strategy", "data analysis", "compliance", "stakeholder engagement", "benchmarking", "documentation", "gri", "supply chain sustainability", "kpis"] },
  { slug: "technical-writer",            title: "Technical Writer",            keywords: ["documentation", "api docs", "style guides", "markdown", "content strategy", "information architecture", "user guides", "knowledge base", "developer documentation", "editing", "cms", "collaboration"] },
];

// ── Public API ──────────────────────────────────────────────────────────

const ROLE_MAP = new Map<string, SeoRole>(ROLES.map((r) => [r.slug, r]));

/** All role slugs, useful for generateStaticParams. */
export function getAllSeoRoleSlugs(): string[] {
  return ROLES.map((r) => r.slug);
}

/** Look up a single role by slug. Returns null when the slug is unknown. */
export function getSeoRole(slug: string): SeoRole | null {
  return ROLE_MAP.get(slug) ?? null;
}

/** Total number of roles in the dataset. */
export const SEO_ROLE_COUNT = ROLES.length;

